apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-namespace.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml

commonLabels:
  app: nginx
  managed-by: argocd

namespace: nginx-app
